### ISSUE TITLE
Build a bigger size for Windows 10

### ISSUE THREAD

**Issue by qo4on** [ful1e5/apple_cursor#87]
I am trying to create a version of Monterey cursors for Windows with size 48 in [Colab](https://colab.research.google.com/):
```
!git clone https://github.com/ful1e5/apple_cursor.git
%cd /content/apple_cursor
!make windows WIN_SIZE=48
```
But I get an error:
```
make[1]: Entering directory '/content/apple_cursor/bitmapper'
make[1]: yarn: Command not found
Makefile:13: recipe for target 'install' failed
make[1]: *** [install] Error 127
make[1]: Leaving directory '/content/apple_cursor/bitmapper'
Makefile:10: recipe for target 'render' failed
make: *** [render] Error 2
```
Does anyone know how to fix this?

**Comment by ful1e5** [comment]
It seems there is `yarn` and other dependencies are missing, which you will find in the [readme#dependencies](https://github.com/ful1e5/apple_cursor#dependencies). 

Note that you have to install both dependencies; external and build.

**Comment by qo4on** [comment]
It still doesn't work.
```
!sudo apt install libx11-dev libxcursor-dev libpng-dev
!curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
!echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
!sudo apt update && sudo apt install yarn
!npm cache clean -f
!npm install -g n
!sudo n stable
!npm i puppeteer
!git clone https://github.com/ful1e5/apple_cursor.git
%cd /content/apple_cursor
!make windows WIN_SIZE=48
```
```
make[1]: Entering directory '/content/apple_cursor/bitmapper'
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[] 0/84[] 4/84[] 7/84[] 10/84[] 14/84[] 17/84[] 20/84[] 21/84[] 24/84[] 28/84[] 32/84[] 33/84[] 36/84[] 39/84[] 42/84[] 47/84[] 51/84[] 55/84[] 59/84[] 64/84[] 68/84[] 74/84[] 78/84[] 82/84[3/4] Linking dependencies...
warning "workspace-aggregator-08c210e6-19a7-469c-8517-1e5f0f6636dd > bigsur > ts-node@10.7.0" has unmet peer dependency "@types/node@*".
[] 84/84[] 0/83[] 3/83[] 0/1432[] 162/1432[] 443/1432[] 671/1432[] 756/1432[] 757/1432[] 881/1432[] 1091/1432[] 1379/1432[] 0/165[] 144/165[4/4] Building fresh packages...
[] 165/165success Saved lockfile.
Done in 12.20s.
yarn run v1.22.19
$ yarn workspace bigsur render
$ yarn build && node dist/index.js
$ npx tsc --build
Generating bitmaps for macOSBigSur
/content/apple_cursor/bitmapper/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x28000020c5a0 


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/content/apple_cursor/bitmapper/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at Interface.<anonymous> (/content/apple_cursor/bitmapper/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
    at Interface.emit (node:events:539:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /usr/share/yarn/lib/cli.js render
Directory: /content/apple_cursor/bitmapper/packages/bigsur
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Makefile:16: recipe for target 'render_bigsur' failed
make[1]: *** [render_bigsur] Error 1
make[1]: Leaving directory '/content/apple_cursor/bitmapper'
Makefile:10: recipe for target 'render' failed
make: *** [render] Error 2
```

**Comment by qo4on** [comment]
Can someone post cursors in resolution 48? The code from this repository doesn't work for me, I can't create it myself.

**Comment by ful1e5** [comment]
[macOSBigSur-White-Windows.zip](https://github.com/ful1e5/apple_cursor/files/9266119/macOSBigSur-White-Windows.zip)
[macOSBigSur-Windows.zip](https://github.com/ful1e5/apple_cursor/files/9266120/macOSBigSur-Windows.zip)
[macOSMonterey-White-Windows.zip](https://github.com/ful1e5/apple_cursor/files/9266121/macOSMonterey-White-Windows.zip)
[macOSMonterey-Windows.zip](https://github.com/ful1e5/apple_cursor/files/9266122/macOSMonterey-Windows.zip)

**Comment by qo4on** [comment]
Thank you!
I found several bugs in the Monterey cursors.
1. Shouldn't default and alternate be mirrored copies of each other? They are different at the moment.
![image](https://user-images.githubusercontent.com/35609308/183156886-835e5f25-3fc4-4820-9e6d-13eef9c0b7af.png)

2. The first 2 frames of Busy and Work cursors are duplicates. They are exactly the same. The angle between the first and the last frames is much greater than average. Both cursors are rotating in the wrong direction.
![image](https://user-images.githubusercontent.com/35609308/183157189-3cdbd1fd-3a2c-443b-8ab9-842a162aefdf.png)

Cursors don't look clear.
